apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: n8n
  name: n8n
  namespace: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: n8n
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: n8n
    spec:
      containers:
        - args:
            - n8n
            - start
          envFrom:
            - secretRef:
                name: n8n-secret
          image: n8nio/n8n
          name: n8n
          resources:
            limits:
              cpu: 900m
              memory: 4Gi
            requests:
              cpu: 600m
              memory: 1Gi
          ports:
            - containerPort: 5678
          volumeMounts:
            - mountPath: /root/.n8n
              name: n8n-claim0
            - mountPath: /opt/workflows
              name: n8n-claim1
      restartPolicy: Always
      volumes:
        - name: n8n-claim0
          persistentVolumeClaim:
            claimName: n8n-claim0
        - name: n8n-claim1
          persistentVolumeClaim:
            claimName: n8n-claim1
