apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: n8n
  name: n8n-svc
  namespace: n8n
spec:
  ports:
    - port: 5678
      protocol: TCP
      targetPort: 5678
  selector:
    io.kompose.service: n8n
  type: LoadBalancer
