apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: default-pvc
  namespace: home-lab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: "openebs-hostpath"
